const PHOTO = {
    beach: '/ec246eb2-6c56-4a2e-aa65-d09ffc9a62c9.jpg',
    cafe: '/5c004c76-d2d5-4fab-8307-e5df0c194dc1.jpg',
    market: '/9e582d3a-c3de-4ac9-a64e-952cdb17a104.jpg',
    food: '/67984159-ee93-4d51-aadd-43522138b92a.jpg',
    view: '/0844eb8a-06d8-4ab3-83ad-92012ae8d8fe.jpg',
}

export const exploreCards = [
    {
        title: '제주 힐링 여행',
        tag: '#제주도 #가족여행',
        region: '제주도',
        image: PHOTO.beach,
        author: '예린',
        rating: '4.9',
    },
    {
        title: '강릉 카페 순례',
        tag: '#강릉 #카페투어',
        region: '강릉',
        image: PHOTO.cafe,
        author: '민수',
        rating: '4.8',
    },
    {
        title: '부산 야경 한 바퀴',
        tag: '#부산 #야경',
        region: '부산',
        image: PHOTO.market,
        author: '서연',
        rating: '4.7',
    },
    {
        title: '제주 우도 자전거 여행',
        tag: '#제주도 #액티비티',
        region: '제주도',
        image: PHOTO.view,
        author: '태호',
        rating: '4.6',
    },
    {
        title: '경주 벚꽃 나들이',
        tag: '#경주 #봄여행',
        region: '경주',
        image: PHOTO.food,
        author: '하은',
        rating: '4.5',
    },
    {
        title: '여수 밤바다 투어',
        tag: '#여수 #야경',
        region: '여수',
        image: PHOTO.beach,
        author: '준호',
        rating: '4.9',
    },
    {
        title: '서울 미식 탐방',
        tag: '#서울 #맛집',
        region: '서울',
        image: PHOTO.food,
        author: '민수',
        rating: '4.4',
    },
    {
        title: '강릉 안목해변 감성샷',
        tag: '#강릉 #사진스팟',
        region: '강릉',
        image: PHOTO.beach,
        author: '예린',
        rating: '4.7',
    },
    {
        title: '부산 감천문화마을',
        tag: '#부산 #문화',
        region: '부산',
        image: PHOTO.view,
        author: '서연',
        rating: '4.8',
    },
    {
        title: '제주 흑돼지 맛집 투어',
        tag: '#제주도 #맛집',
        region: '제주도',
        image: PHOTO.food,
        author: '준호',
        rating: '4.9',
    },
    {
        title: '경주 첨성대 야경',
        tag: '#경주 #야경',
        region: '경주',
        image: PHOTO.view,
        author: '하은',
        rating: '4.6',
    },
    {
        title: '여수 케이블카 여행',
        tag: '#여수 #액티비티',
        region: '여수',
        image: PHOTO.market,
        author: '태호',
        rating: '4.5',
    },
    {
        title: '서울 한강 피크닉',
        tag: '#서울 #힐링',
        region: '서울',
        image: PHOTO.cafe,
        author: '민수',
        rating: '4.3',
    },
    {
        title: '강릉 커피거리 완주',
        tag: '#강릉 #카페투어',
        region: '강릉',
        image: PHOTO.cafe,
        author: '하은',
        rating: '4.8',
    },
]
