import type { PlaceSearchCategory } from './types'

export const PLACE_SEARCH_CATEGORIES: PlaceSearchCategory[] = [
    {
        key: 'all',
        label: '전체',
        placeholder: '가고 싶은 장소를 검색해보세요',
        categoryKey: null,
        suggestions: [],
    },
    {
        key: 'lodging',
        label: '숙소',
        placeholder: '어떤 숙소를 찾고 있나요?',
        categoryKey: 'lodging',
        suggestions: [
            { label: '호텔', includedType: 'hotel' },
            { label: '리조트', includedType: 'resort_hotel' },
            { label: '게스트하우스', includedType: 'guest_house' },
            { label: '호스텔', includedType: 'hostel' },
            { label: '펜션', includedType: 'lodging' },
            { label: '에어비앤비', includedType: 'private_guest_room' },
            { label: '모텔', includedType: 'motel' },
        ],
    },
    {
        key: 'tourist_attraction',
        label: '관광지',
        placeholder: '가고 싶은 명소를 검색해보세요',
        categoryKey: 'attraction',
        suggestions: [
            { label: '박물관', includedType: 'museum' },
            { label: '미술관', includedType: 'art_gallery' },
            { label: '전망대', includedType: 'observation_deck' },
            { label: '테마파크', includedType: 'amusement_park' },
            { label: '공원', includedType: 'park' },
            { label: '유적지', includedType: 'historical_place' },
            { label: '해변', includedType: 'beach' },
            { label: '성', includedType: 'castle' },
        ],
    },
    {
        key: 'restaurant',
        label: '음식점',
        placeholder: '어떤 음식이 먹고 싶나요?',
        categoryKey: 'food',
        suggestions: [
            { label: '현지 맛집', includedType: 'restaurant' },
            { label: '레스토랑', includedType: 'restaurant' },
            { label: '뷔페', includedType: 'buffet_restaurant' },
            { label: '브런치', includedType: 'brunch_restaurant' },
            { label: '패스트푸드', includedType: 'fast_food_restaurant' },
        ],
    },
    {
        key: 'cafe',
        label: '카페',
        placeholder: '어떤 카페를 찾고 있나요?',
        categoryKey: 'cafe',
        suggestions: [
            { label: '카페', includedType: 'cafe' },
            { label: '커피 전문점', includedType: 'coffee_shop' },
            { label: '디저트 카페', includedType: 'dessert_shop' },
            { label: '베이커리', includedType: 'bakery' },
            { label: '브런치 카페', includedType: 'brunch_restaurant' },
            { label: '티하우스', includedType: 'tea_house' },
        ],
    },
    {
        key: 'shopping_mall',
        label: '쇼핑',
        placeholder: '어디서 쇼핑하고 싶나요?',
        categoryKey: 'shopping',
        suggestions: [
            { label: '쇼핑몰', includedType: 'shopping_mall' },
            { label: '백화점', includedType: 'department_store' },
            { label: '전통 시장', includedType: 'market' },
            { label: '편의점', includedType: 'convenience_store' },
            { label: '마트', includedType: 'supermarket' },
            { label: '의류 매장', includedType: 'clothing_store' },
        ],
    },
    {
        key: 'transit_station',
        label: '교통',
        placeholder: '어떤 교통편을 찾고 있나요?',
        categoryKey: 'transport',
        suggestions: [
            { label: '공항', includedType: 'airport' },
            { label: '기차역', includedType: 'train_station' },
            { label: '버스터미널', includedType: 'bus_station' },
            { label: '지하철역', includedType: 'subway_station' },
            { label: '렌터카', includedType: 'car_rental' },
            { label: '페리터미널', includedType: 'ferry_terminal' },
        ],
    },
]
