import type { PlaceSearchCategory } from './types'

export const PLACE_SEARCH_CATEGORIES: PlaceSearchCategory[] = [
    {
        key: 'all',
        label: '전체',
        placeholder: '가고 싶은 장소를 검색해보세요',
        categoryKey: null,
        suggestions: [],
    },
    {
        key: 'lodging',
        label: '숙소',
        placeholder: '어떤 숙소를 찾고 있나요?',
        categoryKey: 'lodging',
        suggestions: [
            '호텔',
            '리조트',
            '게스트하우스',
            '호스텔',
            '펜션',
            '에어비앤비',
            '모텔',
        ],
    },
    {
        key: 'tourist_attraction',
        label: '관광지',
        placeholder: '가고 싶은 명소를 검색해보세요',
        categoryKey: 'attraction',
        suggestions: [
            '박물관',
            '미술관',
            '전망대',
            '테마파크',
            '공원',
            '유적지',
            '해변',
            '성',
        ],
    },
    {
        key: 'restaurant',
        label: '음식점',
        placeholder: '어떤 음식이 먹고 싶나요?',
        categoryKey: 'food',
        suggestions: [
            '현지 맛집',
            '레스토랑',
            '야시장',
            '길거리 음식',
            '뷔페',
            '브런치',
            '패스트푸드',
        ],
    },
    {
        key: 'cafe',
        label: '카페',
        placeholder: '어떤 카페를 찾고 있나요?',
        categoryKey: 'cafe',
        suggestions: [
            '카페',
            '디저트 카페',
            '베이커리',
            '루프탑 카페',
            '브런치 카페',
            '북카페',
        ],
    },
    {
        key: 'shopping_mall',
        label: '쇼핑',
        placeholder: '어디서 쇼핑하고 싶나요?',
        categoryKey: 'shopping',
        suggestions: [
            '쇼핑몰',
            '백화점',
            '전통 시장',
            '아울렛',
            '면세점',
            '편의점',
        ],
    },
    {
        key: 'transit_station',
        label: '교통',
        placeholder: '어떤 교통편을 찾고 있나요?',
        categoryKey: 'transport',
        suggestions: [
            '공항',
            '기차역',
            '버스터미널',
            '지하철역',
            '렌터카',
            '페리터미널',
        ],
    },
]
