package back.backend.domain.admin.entity;

public enum AdminActionType {
    MEMBER_SUSPENDED,
    MEMBER_SUSPENSION_RELEASED,
    SUB_ADMIN_GRANTED,
    SUB_ADMIN_REVOKED,
    INQUIRY_REPLIED,
    COVER_IMAGE_ADDED,
    COVER_IMAGE_ACTIVATED,
    COVER_IMAGE_DEACTIVATED
}
