package back.backend.domain.collaboration.activitylog.infrastructure;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.jdbc.test.autoconfigure.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.ActiveProfiles;

@JdbcTest
@ActiveProfiles("test")
@Import(JdbcTripMemberAccessChecker.class)
class JdbcTripMemberAccessCheckerTest {

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private JdbcTripMemberAccessChecker accessChecker;

    @BeforeEach
    void setUp() {
        jdbcClient.sql("""
                        create table if not exists trip_members (
                            id bigint generated by default as identity primary key,
                            trip_id bigint not null,
                            member_id bigint not null
                        )
                """)
                .update();
        jdbcClient.sql("delete from trip_members").update();
        jdbcClient.sql("insert into trip_members (trip_id, member_id) values (1, 2)")
                .update();
    }

    @Test
    @DisplayName("t1 여행 멤버가 존재하면 접근 가능 결과를 반환한다")
    void t1_isMemberReturnsTrueWhenTripMemberExists() {
        assertThat(accessChecker.isMember(1L, 2L)).isTrue();
    }

    @Test
    @DisplayName("t2 여행 멤버가 존재하지 않으면 접근 불가 결과를 반환한다")
    void t2_isMemberReturnsFalseWhenTripMemberDoesNotExist() {
        assertThat(accessChecker.isMember(1L, 3L)).isFalse();
    }
}
